//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HellfireMiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HellfireMiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03084
        ///03086
        ///03089
        ///03158
        ///03162
        ///03179
        ///03180
        ///03196
        ///03197
        ///03370
        ///03397
        ///03399
        ///06002
        ///08008
        ///08030
        ///08031
        ///08062
        ///08091
        ///08093
        ///08114
        ///08115
        ///08136
        ///08150
        ///08163
        ///08171
        ///08172
        ///08177
        ///08184
        ///08197
        ///08201
        ///08202
        ///08203
        ///08206
        ///08210
        ///08224
        ///08226
        ///08249
        ///08252
        ///08295
        ///08305
        ///08308
        ///08309
        ///08311
        ///08330
        ///08331
        ///08332
        ///08339
        ///08344
        ///08345
        ///08369
        ///08371
        ///08372
        ///08391
        ///08420
        ///08424
        ///08430
        ///08432
        ///08433
        ///08444
        ///08446
        ///08448
        ///08449
        ///08459
        ///08476
        ///08497
        ///08498
        ///08500
        ///08501
        ///08543
        ///08548
        ///08568
        ///08579
        ///08607
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string baseneeds {
            get {
                return ResourceManager.GetString("baseneeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
    }
}
